version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: Set-WinSystemLocale ja-JP
- ps: Start-Sleep -s 10
- ps: Restart-Computer
- ps: Start-Sleep -s 10

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

    echo appveyor_yml

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'


before_deploy:

deploy:
  - provider: GitHub
    auth_token:
      secure: xDUB9jmTodzcvy1twsTYQ8RtANSfUvcFyOfc8df0ut/nwFdiWWS4hlOBqnxz8J/3

    description: It was automatically deployed by AppVeyor CI.

    draft: false
    prerelease: false
    force_update: true

    on:
      #branch: master
      appveyor_repo_tag: true

after_deploy:

