version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64

build_script:
- cmd: >-
    call checkEncoding.bat

    call build-all.bat %PLATFORM% %CONFIGURATION%

    call tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

    echo appveyor_yml

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'


before_deploy:

deploy:
  - provider: GitHub
    auth_token:
      secure: xDUB9jmTodzcvy1twsTYQ8RtANSfUvcFyOfc8df0ut/nwFdiWWS4hlOBqnxz8J/3

    description: It was automatically deployed by AppVeyor CI.

    draft: false
    prerelease: false
    force_update: true

    on:
      appveyor_repo_tag: true
      #branch: master
      configuration: Release
      artifact: .*(All|Exe|Installer).zip$

  - provider: BinTray
    api_key:
      secure: a9zo/A84vMQm/kJN2p2TlvWTEdXv5r7bC5ayOaFKxJokBuRdLdm2EKo2klkc8Yxm

    description: It was automatically deployed by AppVeyor CI.

    username: jakenjarvis
    subject: jakenjarvis
    repo: Generic
    package: sakura-editor-informal
    version: sakura-*$(platform)-$(configuration)*
    publish: true
    override: true
    explode: false

    on:
      appveyor_repo_tag: true

after_deploy:

